// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using THSocialMedia.Infrastructure.EfDbContext;

#nullable disable

namespace THSocialMedia.Infrastructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20260412075025_AddSeedUsers")]
    partial class AddSeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("THSocialMedia.Domain.Entities.ChatMember", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "ConversationId");

                    b.HasIndex("ConversationId");

                    b.ToTable("ChatMembers");
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileUrls")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReplyMsgId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileUrls")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Reactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Like",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Love",
                            Type = 2,
                            UpdatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Angry",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Sad",
                            Type = 4,
                            UpdatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Wow",
                            Type = 5,
                            UpdatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Haha",
                            Type = 6,
                            UpdatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.ReactionPost", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReactionId")
                        .HasColumnType("uuid");

                    b.HasKey("PostId", "UserId");

                    b.HasIndex("ReactionId");

                    b.HasIndex("UserId");

                    b.ToTable("ReactionPosts");
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.Relationship", b =>
                {
                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReceiverId", "SenderId");

                    b.ToTable("Relationships");

                    b.HasData(
                        new
                        {
                            ReceiverId = new Guid("00000000-0000-0000-0000-000000000001"),
                            SenderId = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsDeleted = false,
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AvatarUrl = "",
                            Bio = "Tôi là admin",
                            CreatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gmail.com",
                            FullName = "Nguyễn Admin",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "1234",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AvatarUrl = "",
                            Bio = "Tôi bạn là admin",
                            CreatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Email = "banadmin@gmail.com",
                            FullName = "Nguyễn Bạn Admin",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "1234",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Username = "banadmin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AvatarUrl = "",
                            Bio = "Thích chụp ảnh",
                            CreatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lan.nguyen@gmail.com",
                            FullName = "Nguyễn Ngọc Lan",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "1234",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Username = "ngoclan"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            AvatarUrl = "",
                            Bio = "Đam mê code",
                            CreatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Email = "minh.tran@gmail.com",
                            FullName = "Trần Đức Minh",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "1234",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Username = "ducminh"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            AvatarUrl = "",
                            Bio = "Food reviewer",
                            CreatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hoa.le@gmail.com",
                            FullName = "Lê Thanh Hoa",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "1234",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Username = "thanhhoa"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            AvatarUrl = "",
                            Bio = "Thích đi phượt",
                            CreatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tuan.pham@gmail.com",
                            FullName = "Phạm Anh Tuấn",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "1234",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Username = "anhtuan"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            AvatarUrl = "",
                            Bio = "Yêu âm nhạc",
                            CreatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mai.vu@gmail.com",
                            FullName = "Vũ Xuân Mai",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "1234",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 4, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            Username = "xuanmai"
                        });
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.ChatMember", b =>
                {
                    b.HasOne("THSocialMedia.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Members")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THSocialMedia.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.Comment", b =>
                {
                    b.HasOne("THSocialMedia.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.Message", b =>
                {
                    b.HasOne("THSocialMedia.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THSocialMedia.Domain.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.Post", b =>
                {
                    b.HasOne("THSocialMedia.Domain.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.ReactionPost", b =>
                {
                    b.HasOne("THSocialMedia.Domain.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THSocialMedia.Domain.Entities.Reaction", "Reaction")
                        .WithMany()
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("THSocialMedia.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Reaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("THSocialMedia.Domain.Entities.User", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
